spring:
  cloud:
    function:
      definition: createMovie;getMovie;createRating
    stream:
      default-binder: rabbit
      bindings:
        createMovie-in-0:
          destination: create-movie
          group: create-movie-group
        getMovie-in-0:
          destination: get-movie
          group: get-movie-group
        createRating-out-0:
          destination: create-rating
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

  logging:
    level:
      org.springframework.cloud.stream: DEBUG
      org.springframework.integration: DEBUG
